### ISSUE TITLE
Menü für Kurs-Komponenten

### ISSUE THREAD

**Issue by felixKubicek** [roschaefer/Timetabling#127]
Als Planer möchte ich
die Möglichkeit haben einzelne Komponenten für einen Kurs anzulegen,
um diese in die Gesamtplanung einzubeziehen.

**Comment by felixKubicek** [comment]
- Einzelne Komponenten haben einen bestimmten Typ (Vorlesung, Übung, Projekt, ...)
- Letzte wichtige Änderung am Schema, um alle wichtigen Informationen für ASP Constraints bereitzuhalten

**Comment by roschaefer** [comment]
@felixKubicek dürfte erledigt sein nach #128
