### ISSUE TITLE
Festgelegte Zeitslots für Veranstaltungen im Informatik-Lehramtstudium (Vorlesungen)

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#14]
Als Informatik-Lehramtsstudent möchte ich,
dass die für mich in Frage kommenden Pflichtveranstaltungen gemäß den Regeln der Uni Potsdam je nach Semesterempfehlung nur in ausgewählte Zeitslots gelegt werden,
denn diese Regeln helfen allen Lehramtstudenten dabei, ihre Fächerkombination studieren zu können.

**Comment by roschaefer** [comment]
@wsuser gemäß unserem heutigen Treffen angepasst. Gerne verändern oder kommentieren.

**Comment by felixKubicek** [comment]
Eng gekoppelt mit #125

**Comment by felixKubicek** [comment]
Festgelegte Zeitslots gelten NUR für Bachelor Lehramt!!!
