### ISSUE TITLE
Unverfügbarkeit von Räumen

### ISSUE THREAD

**Issue by felixKubicek** [roschaefer/Timetabling#27]
Als Planer möchte ich,
bestimmte Räume für bestimmte Tage oder Zeitfenster sperren können, sodass kein Termin während dieser Zeit in diesen Raum gelegt wird,
weil mir manche Räume (z.B. im Zweitzugriffsrecht) nur zeitfensterweise zugewiesen werden.

**Comment by roschaefer** [comment]
EDIT: bezieht sich nicht mehr auf Lehrveranstaltungen; Räume deaktivieren statt hinzufügen/löschen; Formulierung.

**Comment by roschaefer** [comment]
EDIT: Bezieht sich nur noch auf sog. "Raumsperren"
