### ISSUE TITLE
Keine mehrfache Raumbelegungen

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#3]
Als Student oder Dozent möchte ich,
dass nicht zur selben Zeit im selben Raum völlig unterschiedliche Kurse gehalten werden,
weil sich die Teilnehmer sonst stören würden.

**Comment by felixKubicek** [comment]
Einzige Ausnahme: Mehrere Veranstaltungen werden aus organisatorischen Gründen aufgrund großer inhaltlicher Übereinstimmung, zu einer Zusammengefasst

**Comment by roschaefer** [comment]
Edit: keine unterschiedlichen Kurse im selben Raum zur selben Zeit.
