### ISSUE TITLE
Neue Lehrkräfte

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#34]
Als Planer möchte ich,
eine neue Lehrkraft in das Timetabling System einfügen,
wenn z.B. ein neuer Mitarbeiter angestellt wird, der eine Übung hält.

**Comment by roschaefer** [comment]
@wsuser haben wir das so richtig verstanden? Sie hatten uns geschrieben: "Für noch unbekannte Dozenten [..] zum Zeitpunkt der Planung können Dummys gesetzt werden[...]" Wir haben daraus zwei Userstories gemacht #27 und dieses hier. Muss der "Dummy" besonders als solcher modelliert werden? Oder kann man wie oben beschrieben auch einfach einen neuen Dozenten namens "Unbekannt" einfügen?

**Comment by wsuser** [comment]
Es müssen in diesen Fällen noch unbekannte Dozenten benutzt werden, die 
aber jeweils als eine bestimmte Person zu betrachten sind. N.N.1, N.N.2 usw.
Nur wenn sie als verschiedene Personen betrachten werden, können 
Konflikte erkannt werden. Wenn N.N.1 beispielweise zur gleichen Zeit in 
zwei LV auftritt.




Am 05.02.2015 um 00:48 schrieb Robert Schäfer:

**Comment by roschaefer** [comment]
@carstenbyl in der Hokus DB stehen bei Kursen manchmal NULL-Werte ("N.N.") im Feld "Lehrkraft". Dann sollen automatisch neue Lehrkräfte erzeugt werden, für jeden NULL-Wert eine.
