### ISSUE TITLE
Konvertierung Datenbank zu Faktendatei

### ISSUE THREAD

**Issue by carstenbyl** [roschaefer/Timetabling#35]

**Comment by roschaefer** [comment]
wollen wir das wirklich im ersten Milestone machen? Nach meiner Schätzung ist das ein sehr großer Haufen Arbeit.

**Comment by carstenbyl** [comment]
Ich wollte zumindest soviel machen, dass wir das asp-encoding damit durchlaufen lassen könnten, falls sich herausstellt, dass alle Daten in der Datenbank vorhanden sind.

**Comment by roschaefer** [comment]
ah moment, von welcher Datenbank ist die Rede? Meinst Du unsere "eigene" Datenbank, die unter  dem Timetabling System liegt oder Hokus+Pulse?

**Comment by carstenbyl** [comment]
ich meinte die hokus-puls-db / xml-file

**Comment by roschaefer** [comment]
Duplikat #24
