### ISSUE TITLE
Raumgröße

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#6]
Als Student oder Dozent möchte ich,
dass meine Lehrveranstaltungen in ausreichend großen Räumen stattfinden,
sonst müssen die Teilnehmer auf dem Boden sitzen und haben keinen Platz zum Schreiben.

**Comment by roschaefer** [comment]
Ist das wirklich ein Hard Constraint?? Wir haben es zz. als Soft Constraint, wobei es immer schlimmer wird je übervoller der Raum wird. Das müsste doch für einen guten Stundenplan reichen?

**Comment by felixKubicek** [comment]
@roschaefer, nein würde es auch als soft-constraint modellieren. Das "hard-constraint" Label war, denke ich, ein Versehen.
