### ISSUE TITLE
Neue Unverfügbarkeit von Lehrkräften hinzufügen

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#65]
Als Planer möchte ich,
nach mündlicher Absprache mit einer Lehrkraft dessen zeitliche Unverfügbarkeit im Timetabling System nachtragen,
damit das Timetabling System diese geänderten Ausgangsdaten berücksichtigt.

**Comment by felixKubicek** [comment]
Just like with the ASP encoding we have to think about pulling different unavailabilities together.
Teacher unavailabilities  are mapped to the Unavailability class (maybe just one Unavailability class with day and timeslot attribute and additionally a polymorphic association to rooms, teachers or whatever  )

**Comment by roschaefer** [comment]
@felixKubicek nach #76 erledigt
