### ISSUE TITLE
Unverfügbarkeiten von Lehrkräften anzeigen

### ISSUE THREAD

**Issue by felixKubicek** [roschaefer/Timetabling#69]
Als Planer möchte ich,
mir für Lehrkräfte eingetragene Unverfügbarkeiten, welche ich in das System eingetragen habe, anzeigen lassen.

**Comment by felixKubicek** [comment]
Eng gekoppelt mit #65

**Comment by roschaefer** [comment]
@felixKubicek erledigt nach #76
