### ISSUE TITLE
Überschneidung von Kursen mit reservierten Zeiten anderer Fakultäten

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#85]
Als Planer möchte ich,
wenn zu gewissen Zeiten die Wahrscheinlichkeit hoch ist, dass einige Kurse Konflikte mit Kursen anderer Fakultäten der gleichen Studienordnung haben, dann sollen die betroffenen Kurse möglichst nicht stattfinden
denn so kann ich die Akzeptanz meiner Raumplanung gegenüber anderen Planern verbessern.

**Comment by felixKubicek** [comment]
@roschaefer konkrete Umsetzung? (hinzufügen externer Studienordnung u. externer Kurse oder einfach über Unverfügbarkeiten (von Studienordnungen))

**Comment by roschaefer** [comment]
@felixKubicek checkout branch ```97_asp_curriculum_unavailabilities```
Dann kannst Du ja mal die zwei Cucumber Szenarios grün machen, die zurzeit noch fehlschlagen. Hatte ich am Mittwoch im Zug noch geschrieben.

**Comment by roschaefer** [comment]
@felixKubicek um die Frage zu beantworten: Nein, es bringt keinen Mehrwert, Studienordnungen oder Kurse durch ein Flag "extern" zu kennzeichnen. Es spielt auch gar keine Rolle fürs Timetabling. Es gibt einfach Sperrzeiten für Studienordnungen wegen externer Ursachen (andere Planer). Aber das kann dem ASP Solver egal sein.
