### ISSUE TITLE
Menü für Studienordnungen: Zuordungen von Modulen

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#87]
Als Planer möchte ich,
die Zuordnung von Modulen zu Studienordnungen so vornehmen, dass ein Modul Pflicht- oder Wahlmodul ist und dass es für ein bestimmtes Semester empfohlen sein kann,
damit diese Information in die Stundenplan-Berechnung einfliessen kann.

**Comment by felixKubicek** [comment]
@wsuser können eigentlich zwei Kurse, die dem gleichen Modul zugeordnet sind, unterschiedliche Semesterempfehlungen haben ? Oder ist es ausreichend wenn alle Kurse für ein bestimmtes Modul die gleiche Semesterempfehlung haben? (gleiches für Pflicht: ist ein Modul Pflicht oder kann auch eine Kurs Pflichtveranstaltung sein ?)

**Comment by wsuser** [comment]
Die Lehrangebote(Kurse) können unterschiedliche Semesterempfehlungen 
haben, wenn sie für mehrere Studiengänge angeboten werden. Zum Beispiel 
"Praxis der Programmierung" Pflichtmodul im Studiengang BSc 0Inf/CS mit 
Empfehlung 2. Semester. Gleichzeitig  im Master-Studiengang der 
Bioinformatik oder Geoinformation und Visualisierung als Brückenmodul 
belegbar. Dann mit der Semesterempfehlung 7. Semester.

Die Differenzierung der Emfehlungen nach Studiengängen wird gegenwärtig 
in HOKUS jedoch nicht abgefragt. Die dortige Angabe bezieht sich auf 
unsere Informatik-Studiengänge. (Auch unser Lehramt wird da nicht 
richtig berücksichtigt.)




Am 25.02.2015 um 14:25 schrieb Felix Kubicek:

**Comment by roschaefer** [comment]
![er1](https://cloud.githubusercontent.com/assets/2110676/6378038/b817364c-bd28-11e4-9c51-ae4347c53c36.png)
Hier sind zwei Beispiele, wie wir uns das vorstellen
![er2](https://cloud.githubusercontent.com/assets/2110676/6378042/c056b30a-bd28-11e4-84f3-7bca7a93d957.png)
Die Frage ist: Ist das Modul über eine Semesterempfehlung mit der Studienordnung verknüpft? Und erhalten dann alle Kurse dieses Moduls dessen Empfehlungen? Oder müssen aus irgendwelchen Gründen Kurse unabhängig vom Modul Empfehlungen bekommen?

**Comment by roschaefer** [comment]
![timetablinger_dia](https://cloud.githubusercontent.com/assets/2110676/6415456/7a046834-be9f-11e4-90c9-54522123ab2c.png)
Wird jetzt so implementiert

**Comment by roschaefer** [comment]
@felixKubicek since #96 we can assign modules to curricula. We need to save if it's a mandatory module or not. Do you want to continue on this issue, or do you want to close this issue and open a new one?

**Comment by felixKubicek** [comment]
@roschaefer I'll continue this issue
