### ISSUE TITLE
Fahrtzeiten

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#9]
Als Student möchte ich,
ausreichend Zeit haben um zwischen Veranstaltungen zweier Campus hin- und herzureisen,
sonst würde ich den Beginn der nachfolgenden Veranstaltungen verpassen.

**Comment by felixKubicek** [comment]
... dadurch schon berücksichtigt, dass Termine (mit Länge 1,5 h) 2 h slots zugewiesen werden, wodurch der Termin flexibel im Zeitfenster nach vorne/hinten verschoben werden kann ...
