### ISSUE TITLE
Fix Deployment/Capistrano Configuration

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/Timetabling#91]
atm ```cap production deploy``` doesn't restart the passenger server on the new release

**Comment by roschaefer** [comment]
@felixKubicek not fixed yet
If I run ```cap production deploy``` with a running phusion passenger on the server, I get the followinig
```
DEBUG [c2094ceb] 	rm: 
DEBUG [c2094ceb] 	cannot remove `/home/tt/Timetabling/releases/20150220221320/tmp/pids/passenger.80.pid.lock'
DEBUG [c2094ceb] 	: Permission denied
DEBUG [c2094ceb] 	
DEBUG [c2094ceb] 	rm: cannot remove `/home/tt/Timetabling/releases/20150220224855/tmp/pids/passenger.80.pid.lock': Permission denied
```

**Comment by felixKubicek** [comment]
@roschaefer just delete files and give it another try

**Comment by roschaefer** [comment]
@felixKubicek already done. The server is currently running. 
The problem is: I want a non-interactive single-command that just restarts the server. I start the server with ```rvmsudo passenger ...``` which will create files in ```releases/[some_numbers]/tmp/pids/``` that are owned by ```root``` and not by ```tt```. Making ```cap production deploy``` incapable of deleting them.

**Comment by roschaefer** [comment]
@felixKubicek okay, I've found the problem(s):

1. If you start passenger with the ```--user``` parameter, passenger will switch to root only for acquiring port 80 and eventually switch back to the specified user.
2. If you pass the symlinked directory on the command line like ```passenger start path/to/symlinked/directory```, passenger will restart on the new release after deployment

So the full command to start the server in the very beginning is (from /home/tt/):
````rvmsudo passenger start Timetabling/current -a 141.89.48.35 -p 80 -e production --user tt -d````

Every single parameter is important.

Afterwards, ```cap production deploy``` and ```cap production deploy:restart``` *should* run without any errors or permission denials.
